# Generated by Django 5.2.8 on 2025-12-07 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=100, null=True)),
                ('create_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(max_length=255)),
                ('task_status', models.CharField(choices=[('1', 'Não iniciado'), ('2', 'Em andamento'), ('3', 'Finalizado')])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
